apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiU01vcm96b3ZJVCIsInBhc3N3b3JkIjoiZ2hwX21NdWM0NXVjbGozeHhOV3pQTEZrWkxQWEFDeWdZMzBKTEhQbSIsImVtYWlsIjoicy5tb3Jvem92Lml0QGdtYWlsLmNvbSIsImF1dGgiOiJVMDF2Y205NmIzWkpWRHBuYUhCZmJVMTFZelExZFdOc2FqTjRlRTVYZWxCTVJtdGFURkJZUVVONVoxa3pNRXBNU0ZCdCJ9fX0=
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
